---
- name: Instalacja pakietów nmap i sysstat
  hosts: all
  become: yes
  tasks:
    - name: Aktualizacja listy pakietow
      apt:
        update_cache: yes

    - name: Instalacja nmap
      apt:
        name: nmap
        state: present

    - name: Instalacja sysstat
      apt:
        name: sysstat
        state: present
